name       : telegramqml
version    : 2.0.0
release    : 2
source     :
    - https://github.com/Aseman-Land/TelegramQML/archive/v2.0.0.tar.gz : 6fa519a58eebed0028eb34149198309ecf9901c8d706744d9eb197c92d485427
license    : GPL-3.0
component  : programming
summary    : Telegram API tools for QtQml and Qml.
description: |
    Telegram API tools for QtQml and Qml.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - libqtelegram-ae-devel
setup      : |
    mkdir build
build      : |
    cd build
    qmake -r .. QMAKE_CFLAGS_ISYSTEM= CONFIG+=typeobjects \
        BUILD_MODE+=lib \
        PREFIX=$installdir/usr \
        INSTALL_HEADERS_PREFIX=$installdir/usr/include \
        INSTALL_LIBS_PREFIX=$installdir/%libdir%
    %make
install    : |
    cd build
    %make_install
